services:
  db:
    container_name: db_sge
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
    - "5432:5432"
    networks:
      - sge-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sge
    ports:
      - "8000:8000"
    networks:
      - sge-network
    env_file:
      - .env
    depends_on:
      - db

networks:
  sge-network:
    driver: bridge
