services:
  db:
    container_name: db_sge
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - sge-network

  sge:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    container_name: sge
    ports:
      - "8000:8000"
    networks:
      - sge-network
    volumes:
      - static_data:/sge/static
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    build: 
      context: ./nginx
    container_name: nginx_sge
    ports:
      - "80:80"
    volumes:
      - static_data:/sge/static
    networks:
      - sge-network
    depends_on:
      - sge

volumes:
  static_data:

networks:
  sge-network:
    driver: bridge
