version: "3.11"

services:
  web:
    build: .
    container_name: sge-web
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/sge
    networks:
      - sge-network

networks:
  sge-network:
    driver: bridge
